### ISSUE TITLE
pod try appears to be broken in Cocoapods 0.37.0

### ISSUE THREAD

**Issue by pwillsey** [CocoaPods/cocoapods-try#30]
When I attempt to use pod try on any cocoapod in cocoapods v0.37.0 I get this message:

[!] Unable to find any project in the source files of the Pod: /private/tmp/CocoaPods/Try/PODNAME

If I go into that directory it seems like everything has been stripped out except the README.md, LICENSE and the folder containing the actual pod source files.

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/cocoapods-try/commit/2ae4b1cdb2bc8486f661acd20986de3f9f8c0b8f.
