### ISSUE TITLE
Permissions on Info.plist differ from cache (readonly)

### ISSUE THREAD

**Issue by ianbarber** [CocoaPods/cocoapods-try#31]
For a pod try-able sample (distributed in a zip file with the library) I'm working on, it would be convenient to be able to edit the Info.plist (add a URL type), but that comes locked (read only perms). However, in the Cache dir the user has rw perms. 

~/Library/Caches/Cocoapods/Pods/Releases...
-rw-r--r--   1 ianbarber  eng   949  6 May 18:33 Info.plist

/tmp/CocoaPods/Try...
-r--r--r--   1 ianbarber  wheel   949 30 Apr 12:06 Info.plist

I guess this is happening during the copy from the cache? This is using 0.44, but issue happened on previous version too.

**Comment by segiddins** [comment]
Yeah, the `Installer` is what changes the permissions, not the downloader.

**Comment by ianbarber** [comment]
Makes sense. Any code/plist file from the samples that's kept in pod by preserve_path is going to go through the regular install processing, so mostly end up readonly. This is probably OK in most cases, but is there any value in making them readable in the pod try case - these files are on there for a demo, so it would be nice for people to be able to try modifications/supplying configuration without having to unlock each file?

**Comment by segiddins** [comment]
No, definitely agree that pod try should lock anything. I'll see what I can do to make a backwards compatible fix. 

-Samuel E. Giddins

On May 6, 2015, at 9:50 PM, Ian Barber <notifications@github.com> wrote:

Makes sense. Any code/plist file from the samples that's kept in pod by preserve_path is going to go through the regular install processing, so mostly end up readonly. This is probably OK in most cases, but is there any value in making them readable in the pod try case - these files are on there for a demo, so it would be nice for people to be able to try modifications/supplying configuration without having to unlock each file?

**Comment by segiddins** [comment]
This will be fixed in the next CocoaPods release, thanks for reporting this @ianbarber!
