### ISSUE TITLE
Post install user prompt / script?

### ISSUE THREAD

**Issue by domesticmouse** [CocoaPods/cocoapods-try#33]
On attempting to use `pod try` with `Google-Maps-iOS-SDK` we wind up with a sample sans API Key that will crash if the user just hits run.

It'd be nice to have some post install script driven interaction where by we can direct the user to get an API Key, and then splice it into the sample to make it work out of the box. How can we achieve this with `pod try`?

**Comment by segiddins** [comment]
That's currently not possible, but maybe have an `#error` in the source of the example that the user has to replace for it to compile, so you can give a friendlier error message?

**Comment by domesticmouse** [comment]
Thanks, that will do!

**Comment by orta** [comment]
The point of this issue is legit, would love for `pod try` to look for a file and have the option of running it.

Any feelings on what that file could be, I had debated `configure` but that could do something wrong on c projects. `.pod-try` ?

**Comment by neonichu** [comment]
For the API keys, simply adding cp-keys to the example Podfile could work - would require users to install it if they don't have, though.

**Comment by orta** [comment]
this ideally should be possible with the answer to #38

**Comment by neonichu** [comment]
Implemented by #39
