### ISSUE TITLE
Best way to recursively update submodules in pod try?

### ISSUE THREAD

**Issue by DenHeadless** [CocoaPods/cocoapods-try#46]
Hey!

I'm using .cocoapods.yml to pull all submodules into project to get example project running. Commands are detected, project opened, however it does not seem like git commands were executed. Here's output of pod try command:

```bash
pod --version
1.0.0.beta.2
```

```bash
pod try DTTableViewManager
```

```
Running Pre-Install Commands
In order to try this pod, CocoaPods-Try needs to run the following command:
 - git submodule foreach --recursive git submodule update --init

Press return to run these command, or press `ctrl + c` to stop trying this pod.

    $ /bin/bash -ec git submodule foreach --recursive git submodule update
    --init
Opening '/private/var/folders/fb/wfd_w9kn7bqf86gm9dpk0wg40000gn/T/CocoaPods/Try/DTTableViewManager/Example/DTTableViewManager.xcodeproj'
```

Contents of .cocoapods.yml:

```
try:
  install:
    pre:
      - git submodule foreach --recursive git submodule update --init
```

What do you think?

**Comment by kylef** [comment]
Your command won't do anything since it depends on the submodules existing first (which they don't):

```shell
$ git submodule foreach --recursive git submodule update --init
```

Since there are no checked out submodules, `git submodule foreach` won't run the command anywhere. Check the documentation for `git submodule foreach`:

> Evaluates an arbitrary shell command in each checked out submodule.

You should instead use the following command:

```shell
$ git submodule update --init --recursive
```

**Comment by DenHeadless** [comment]
Thank you very much, it worked!
