### ISSUE TITLE
Cocoa pods 1.0.0.beta.2 error

### ISSUE THREAD

**Issue by kylebrowning** [CocoaPods/cocoapods-try#47]
Trying ComponentKit
Performing CocoaPods Installation
[!] The dependency `ComponentKit (from `../..`)` is not used in any concrete target.

**Comment by segiddins** [comment]
That's not an issue with CocoaPods try, but rather the componentKit demo podfile hasn't been updated for 1.0.

**Comment by kylebrowning** [comment]
Thanks.
