### ISSUE TITLE
Could `pod try` source projects from a separate Git repo?

### ISSUE THREAD

**Issue by perotinus** [CocoaPods/cocoapods-try#53]
🌈
We build several pods, and among them is a pod that includes copies of our samples that are hosted in GitHub: https://cocoapods.org/pods/Google includes samples that are downloaded from https://github.com/googlesamples/google-services/tree/master/ios.

It would be great if `pod try` could download the samples from here, rather than us having to bundle them in the pod's archive. Is this something that you think would be a reasonable addition? I'm not sure how exactly it would work: it could be a Podspec syntax addition, or perhaps a file that, if included in the source, tells `pod try` to look in the repo that's listed in that file.

**Comment by segiddins** [comment]
Could already download stuff via https://github.com/CocoaPods/cocoapods-try/blob/master/lib/pod/try_settings.rb#L16

**Comment by perotinus** [comment]
D'oh! Sorry about that: I should have looked there too.

I'll close this, and open a new issue if that doesn't work for what we need, but it looks like it should. Thanks!
