### ISSUE TITLE
Add a name flag for try by URL

### ISSUE THREAD

**Issue by rockwotj** [CocoaPods/cocoapods-try#54]
Right now I have a repo like so: https://ada.csse.rose-hulman.edu/rosefire/ios-sdk/tree/master

I want to be able to run `pod try https://ada.csse.rose-hulman.edu/rosefire/ios-sdk.git`

The issue is right here, [it's grabing it from the repo URL](https://github.com/CocoaPods/cocoapods-try/blob/master/lib/pod/command/try.rb#L101), but I want to use a different name. Or perhaps it would be better to grab the `.podspec` file from the root? There should only be one such file right?

**Comment by segiddins** [comment]
If you specify a path to the `.podspec` instead of the `.git`, it'll do just that

**Comment by rockwotj** [comment]
So (here is the podspec)[https://ada.csse.rose-hulman.edu/rosefire/ios-sdk/blob/master/Rosefire.podspec] and I get this error, is there something else I should be doing, or I using the wrong URL?

```
$ pod try https://ada.csse.rose-hulman.edu/rosefire/ios-sdk/raw/master/Rosefire.podspec
 > Git download
[!] git clone https://ada.csse.rose-hulman.edu/rosefire/ios-sdk/raw/master/Rosefire.podspec /var/folders/z1/foobar/T/CocoaPods/Try/Rosefire.podspec --template= --single-branch --depth 1

Cloning into '/var/folders/foobar/T/CocoaPods/Try/Rosefire.podspec'...
fatal: repository 'https://ada.csse.rose-hulman.edu/rosefire/ios-sdk/raw/master/Rosefire.podspec/' not found
```

**Comment by segiddins** [comment]
ah I'm sorry, I must've mis-read the code

**Comment by rockwotj** [comment]
@segiddins I submitted #55 to solve this, please take a look if you can 😃
